/**
 * Localized promo course data for the CoursePromoCarousel.
 * Each course entry uses i18n keys: promo.course.{id}.{field}
 * The t() function resolves them from the active locale.
 */

export interface PromoCourseData {
  id: number;
  /** i18n key for title */
  titleKey: string;
  /** i18n key for description */
  descriptionKey: string;
  /** i18n key for tag */
  tagKey: string;
  /** i18n key for duration */
  durationKey: string;
  image: string;
  url: string;
  tagColor: string;
  levelKey: string;
  levelColor: string;
  rating: number;
  isNew?: boolean;
  isHot?: boolean;
}

export const promoCourseIds: PromoCourseData[] = [
  { id: 1, titleKey: "promo.course.1.title", descriptionKey: "promo.course.1.description", tagKey: "promo.course.1.tag", durationKey: "promo.course.1.duration", image: "/courses/sysadmin.jpg", url: "https://stepik.org/a/207061", tagColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isNew: true },
  { id: 2, titleKey: "promo.course.2.title", descriptionKey: "promo.course.2.description", tagKey: "promo.course.2.tag", durationKey: "promo.course.2.duration", image: "/courses/sql-database.jpg", url: "https://stepik.org/a/210134", tagColor: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.9, isHot: true },
  { id: 3, titleKey: "promo.course.3.title", descriptionKey: "promo.course.3.description", tagKey: "promo.course.3.tag", durationKey: "promo.course.3.duration", image: "/courses/javascript-real.jpg", url: "https://stepik.org/a/212445", tagColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7, isNew: true },
  { id: 4, titleKey: "promo.course.4.title", descriptionKey: "promo.course.4.description", tagKey: "promo.course.4.tag", durationKey: "promo.course.4.duration", image: "/courses/php-real.jpg", url: "https://stepik.org/a/253456", tagColor: "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.6 },
  { id: 5, titleKey: "promo.course.5.title", descriptionKey: "promo.course.5.description", tagKey: "promo.course.5.tag", durationKey: "promo.course.5.duration", image: "/courses/docker.jpg", url: "https://stepik.org/a/205094", tagColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isHot: true },
  { id: 6, titleKey: "promo.course.6.title", descriptionKey: "promo.course.6.description", tagKey: "promo.course.6.tag", durationKey: "promo.course.6.duration", image: "/courses/redis.jpg", url: "https://stepik.org/a/222859", tagColor: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.7, isNew: true },
  { id: 7, titleKey: "promo.course.7.title", descriptionKey: "promo.course.7.description", tagKey: "promo.course.7.tag", durationKey: "promo.course.7.duration", image: "/courses/monitoring-real.jpg", url: "https://stepik.org/a/221029", tagColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.6 },
  { id: 8, titleKey: "promo.course.8.title", descriptionKey: "promo.course.8.description", tagKey: "promo.course.8.tag", durationKey: "promo.course.8.duration", image: "/courses/assembler.jpg", url: "https://stepik.org/a/238534", tagColor: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300", levelKey: "common.level.advanced", levelColor: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300", rating: 4.9, isHot: true },
  { id: 9, titleKey: "promo.course.9.title", descriptionKey: "promo.course.9.description", tagKey: "promo.course.9.tag", durationKey: "promo.course.9.duration", image: "/courses/golang.jpg", url: "https://stepik.org/a/240000", tagColor: "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isNew: true },
  { id: 10, titleKey: "promo.course.10.title", descriptionKey: "promo.course.10.description", tagKey: "promo.course.10.tag", durationKey: "promo.course.10.duration", image: "/courses/react-native.png", url: "https://stepik.org/a/252698", tagColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7 },
  { id: 11, titleKey: "promo.course.11.title", descriptionKey: "promo.course.11.description", tagKey: "promo.course.11.tag", durationKey: "promo.course.11.duration", image: "/courses/clickhouse-basics.jpg", url: "https://stepik.org/a/240384", tagColor: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.6 },
  { id: 12, titleKey: "promo.course.12.title", descriptionKey: "promo.course.12.description", tagKey: "promo.course.12.tag", durationKey: "promo.course.12.duration", image: "/courses/mongodb-basics.jpg", url: "https://stepik.org/a/206417", tagColor: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7 },
  { id: 13, titleKey: "promo.course.13.title", descriptionKey: "promo.course.13.description", tagKey: "promo.course.13.tag", durationKey: "promo.course.13.duration", image: "/courses/video-director.jpg", url: "https://stepik.org/a/208571", tagColor: "bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.5 },
  { id: 14, titleKey: "promo.course.14.title", descriptionKey: "promo.course.14.description", tagKey: "promo.course.14.tag", durationKey: "promo.course.14.duration", image: "/courses/vibe-coding.png", url: "https://stepik.org/a/260000", tagColor: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.9, isNew: true, isHot: true },
  { id: 15, titleKey: "promo.course.15.title", descriptionKey: "promo.course.15.description", tagKey: "promo.course.15.tag", durationKey: "promo.course.15.duration", image: "/courses/java.png", url: "https://stepik.org/a/261000", tagColor: "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isNew: true },
  { id: 16, titleKey: "promo.course.16.title", descriptionKey: "promo.course.16.description", tagKey: "promo.course.16.tag", durationKey: "promo.course.16.duration", image: "/courses/web-dev-new.png", url: "https://stepik.org/a/262000", tagColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7, isHot: true },
  { id: 17, titleKey: "promo.course.17.title", descriptionKey: "promo.course.17.description", tagKey: "promo.course.17.tag", durationKey: "promo.course.17.duration", image: "/courses/mobile-dev-new.png", url: "https://stepik.org/a/263000", tagColor: "bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.6 },
  { id: 18, titleKey: "promo.course.18.title", descriptionKey: "promo.course.18.description", tagKey: "promo.course.18.tag", durationKey: "promo.course.18.duration", image: "/courses/git.png", url: "https://stepik.org/a/264000", tagColor: "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.9, isHot: true },
  { id: 19, titleKey: "promo.course.19.title", descriptionKey: "promo.course.19.description", tagKey: "promo.course.19.tag", durationKey: "promo.course.19.duration", image: "/courses/laravel.png", url: "https://stepik.org/a/265000", tagColor: "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.8, isNew: true },
  { id: 20, titleKey: "promo.course.20.title", descriptionKey: "promo.course.20.description", tagKey: "promo.course.20.tag", durationKey: "promo.course.20.duration", image: "/courses/cpp-new.png", url: "https://stepik.org/a/266000", tagColor: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7 },
  { id: 21, titleKey: "promo.course.21.title", descriptionKey: "promo.course.21.description", tagKey: "promo.course.21.tag", durationKey: "promo.course.21.duration", image: "/courses/databases.jpg", url: "https://stepik.org/a/267000", tagColor: "bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.6 },
  { id: 22, titleKey: "promo.course.22.title", descriptionKey: "promo.course.22.description", tagKey: "promo.course.22.tag", durationKey: "promo.course.22.duration", image: "/courses/sysadmin.jpg", url: "https://stepik.org/a/268000", tagColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.5 },
  { id: 23, titleKey: "promo.course.23.title", descriptionKey: "promo.course.23.description", tagKey: "promo.course.23.tag", durationKey: "promo.course.23.duration", image: "/courses/blender-3d.jpg", url: "https://stepik.org/a/270000", tagColor: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7, isNew: true },
  { id: 24, titleKey: "promo.course.24.title", descriptionKey: "promo.course.24.description", tagKey: "promo.course.24.tag", durationKey: "promo.course.24.duration", image: "/courses/docker-step.png", url: "https://stepik.org/a/205094", tagColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8 },
  { id: 25, titleKey: "promo.course.25.title", descriptionKey: "promo.course.25.description", tagKey: "promo.course.25.tag", durationKey: "promo.course.25.duration", image: "/courses/powerbi.jpg", url: "https://stepik.org/a/271000", tagColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.6, isNew: true },
  { id: 26, titleKey: "promo.course.26.title", descriptionKey: "promo.course.26.description", tagKey: "promo.course.26.tag", durationKey: "promo.course.26.duration", image: "/courses/neural-n8n.jpg", url: "https://stepik.org/a/272000", tagColor: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isNew: true, isHot: true },
  { id: 27, titleKey: "promo.course.27.title", descriptionKey: "promo.course.27.description", tagKey: "promo.course.27.tag", durationKey: "promo.course.27.duration", image: "/courses/cybersecurity.jpg", url: "https://stepik.org/a/273000", tagColor: "bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.7, isHot: true },
  { id: 28, titleKey: "promo.course.28.title", descriptionKey: "promo.course.28.description", tagKey: "promo.course.28.tag", durationKey: "promo.course.28.duration", image: "/courses/testing-qa.jpg", url: "https://stepik.org/a/274000", tagColor: "bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.6, isNew: true },
  { id: 29, titleKey: "promo.course.29.title", descriptionKey: "promo.course.29.description", tagKey: "promo.course.29.tag", durationKey: "promo.course.29.duration", image: "/courses/sound-design.jpg", url: "https://stepik.org/a/275000", tagColor: "bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.5 },
  { id: 30, titleKey: "promo.course.30.title", descriptionKey: "promo.course.30.description", tagKey: "promo.course.30.tag", durationKey: "promo.course.30.duration", image: "/courses/csharp.jpg", url: "https://stepik.org/a/276000", tagColor: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.7, isNew: true },
  { id: 31, titleKey: "promo.course.31.title", descriptionKey: "promo.course.31.description", tagKey: "promo.course.31.tag", durationKey: "promo.course.31.duration", image: "/courses/sound-design.jpg", url: "https://stepik.org/a/277000", tagColor: "bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.6 },
  { id: 32, titleKey: "promo.course.32.title", descriptionKey: "promo.course.32.description", tagKey: "promo.course.32.tag", durationKey: "promo.course.32.duration", image: "/courses/golang.jpg", url: "https://stepik.org/a/278000", tagColor: "bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8 },
  { id: 33, titleKey: "promo.course.33.title", descriptionKey: "promo.course.33.description", tagKey: "promo.course.33.tag", durationKey: "promo.course.33.duration", image: "https://ui3adtb308.a.trbcdn.net/Написание%20научных%20статей%20v2.jpg", url: "https://stepik.org/a/279000", tagColor: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300", levelKey: "common.level.intermediate", levelColor: "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300", rating: 4.7, isNew: true },
  { id: 34, titleKey: "promo.course.34.title", descriptionKey: "promo.course.34.description", tagKey: "promo.course.34.tag", durationKey: "promo.course.34.duration", image: "https://ui3adtb308.a.trbcdn.net/Написание%20курсовых,%20дипломных%20работ.jpg", url: "https://stepik.org/a/280000", tagColor: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300", levelKey: "common.level.beginner", levelColor: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300", rating: 4.8, isNew: true, isHot: true },
];
