#!/usr/bin/env node

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  Maestria LMS — Unified Setup & Dev Launcher
 * ═══════════════════════════════════════════════════════════════════════════
 *
 *  Uses scripts/lib/env-manager.js as single source of truth for:
 *  - environment parsing / writing
 *  - port detection
 *  - database provider auto-detection
 *  - package manager detection
 *
 *  Supports: SQLite | PostgreSQL | MongoDB
 * ═══════════════════════════════════════════════════════════════════════════
 */

const { execSync, spawn } = require("child_process");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const ENV_LOCAL_FILE = path.join(ROOT, ".env.local");
const ENV_EXAMPLE_FILE = path.join(ROOT, ".env.example");

// ─── Import unified env manager ───
const env = require("./lib/env-manager");

// ─── Colors ───
const useColor =
  process.platform !== "win32" || !!process.env.WT_SESSION || !!process.env.TERM;
const C = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  red: "\x1b[31m",
  blue: "\x1b[34m",
  bold: "\x1b[1m",
};
const color = (str, c) => (useColor ? `${c}${str}${C.reset}` : str);
const ok = (s) => color(`✓ ${s}`, C.green);
const info = (s) => color(`› ${s}`, C.cyan);
const warn = (s) => color(`! ${s}`, C.yellow);
const err = (s) => color(`✗ ${s}`, C.red);
const head = (s) => color(s, C.bold);
const dbColor = (provider) => {
  const colors = { sqlite: C.cyan, postgresql: C.blue, mongodb: C.green };
  return colors[provider] || C.cyan;
};

// ─── Helpers ───

function generateEnvExample(appPort) {
  return `# ═══════════════════════════════════════════════════
# Maestria LMS — Environment Configuration
# Auto-generated by setup.js
# ═══════════════════════════════════════════════════

# ─── Database ───
# Supported: sqlite, postgresql, mongodb
DATABASE_PROVIDER=sqlite
DATABASE_URL=file:./prisma/data.db

# ─── NextAuth ───
NEXTAUTH_URL=http://localhost:${appPort}
# Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
NEXTAUTH_SECRET=

# ─── CDN & Assets ───
NEXT_PUBLIC_CDN_URL=https://ui3adtb308.a.trbcdn.net
NEXT_PUBLIC_SITE_URL=https://maestria.edu

# ─── S3 Storage (optional) ───
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_ENDPOINT=https://s3c3.001.gpucloud.ru
S3_BUCKET_NAME=maestria-lms
S3_REGION=auto

# ─── Development ───
ALLOW_SEED_DATA=true
`;
}

/**
 * Warn if .env.local overrides critical DATABASE_* keys differently from .env
 */
function checkEnvConflict() {
  const base = env.parseEnv(ENV_FILE);
  const local = env.parseEnv(ENV_LOCAL_FILE);

  const keys = ["DATABASE_PROVIDER", "DATABASE_URL"];
  const conflicts = [];

  for (const key of keys) {
    if (local[key] && base[key] && local[key] !== base[key]) {
      conflicts.push(key);
    }
  }

  if (conflicts.length > 0) {
    console.log(warn(`.env.local overrides .env for: ${conflicts.join(", ")}`));
    console.log(warn("Next.js loads .env.local AFTER .env, so those values win."));
    console.log(info("If this is unintentional, remove them from .env.local"));
  }
}

/**
 * Ensure environment is correctly configured.
 */
async function validateAndGenerateEnv(ports, forcedProvider) {
  const envVars = env.parseEnv(ENV_FILE);
  const envLocalVars = env.parseEnv(ENV_LOCAL_FILE);
  const allVars = { ...envVars, ...envLocalVars };

  let changed = false;
  let dbConfig;

  // ── Determine provider ──
  if (forcedProvider) {
    dbConfig = {
      provider: forcedProvider,
      url: env.getUrlTemplate(forcedProvider, ports[forcedProvider === "postgresql" ? "postgresql" : "mongodb"]),
      reason: `Manually selected: ${forcedProvider}`,
    };
  } else if (envVars.DATABASE_PROVIDER && envVars.DATABASE_URL) {
    dbConfig = {
      provider: envVars.DATABASE_PROVIDER,
      url: envVars.DATABASE_URL,
      reason: "Using existing configuration",
    };
  } else {
    dbConfig = env.detectOptimalConfig(ports);
  }

  // Update .env
  const updates = {};
  if (envVars.DATABASE_PROVIDER !== dbConfig.provider) {
    updates.DATABASE_PROVIDER = dbConfig.provider;
    changed = true;
  }
  if (envVars.DATABASE_URL !== dbConfig.url) {
    updates.DATABASE_URL = dbConfig.url;
    changed = true;
  }

  const expectedUrl = `http://localhost:${ports.app}`;
  if (allVars.NEXTAUTH_URL !== expectedUrl) {
    updates.NEXTAUTH_URL = expectedUrl;
    changed = true;
  }

  if (changed) {
    env.mergeEnv(ENV_FILE, updates);
    console.log(ok("Configuration saved to .env"));
  }

  console.log(info(`Database: ${color(dbConfig.provider, dbColor(dbConfig.provider))}`));
  console.log(info(`Reason: ${dbConfig.reason}`));
  console.log(info(`URL: ${dbConfig.url}`));

  // NEXTAUTH_SECRET → write to .env.local (security)
  if (!allVars.NEXTAUTH_SECRET) {
    const secret = crypto.randomBytes(32).toString("base64");
    env.mergeEnv(ENV_LOCAL_FILE, { NEXTAUTH_SECRET: secret });
    console.log(ok("Generated NEXTAUTH_SECRET in .env.local"));
  }

  // Generate .env.example
  fs.writeFileSync(ENV_EXAMPLE_FILE, generateEnvExample(ports.app), "utf8");

  // Conflict check
  checkEnvConflict();

  return dbConfig;
}

// ─── Commands ───

function runCommand(cmd, label, cwd = ROOT) {
  console.log(info(label || `Running: ${cmd}`));
  try {
    const start = Date.now();
    execSync(cmd, { cwd, stdio: "inherit", shell: true });
    const elapsed = ((Date.now() - start) / 1000).toFixed(1);
    console.log(ok(`${label || cmd} (${elapsed}s)`));
  } catch {
    console.log(err(`${label || cmd} failed`));
    process.exit(1);
  }
}

function runPrerequisites(pm, provider) {
  runCommand(`${pm.cmd} install`, "Installing dependencies");

  if (provider === "mongodb") {
    console.log(info("MongoDB detected — skipping Prisma"));
    return;
  }

  runCommand(`${pm.cmd} run db:generate`, "Generating Prisma client");
  runCommand(`${pm.cmd} run db:push`, "Pushing schema to database");
}

// ─── Dev Server ───

function startDevServer(pm, port) {
  const tryStart = (startPort, attempts = 0) => {
    if (attempts > 10) {
      console.log(err("Failed to find available port after 10 attempts"));
      process.exit(1);
    }

    console.log("");
    console.log(head(`  🚀 Maestria LMS starting at ${color(`http://localhost:${startPort}`, C.green)}`));
    console.log("");

    const child = spawn(pm.cmd, ["next", "dev", "--port", String(startPort)], {
      cwd: ROOT,
      stdio: ["inherit", "pipe", "pipe"],
      shell: process.platform === "win32",
    });

    let hasError = false;

    child.stderr.on("data", (data) => {
      const msg = data.toString();
      process.stderr.write(data);
      if (msg.includes("EADDRINUSE")) {
        hasError = true;
        console.log(warn(`Port ${startPort} is in use, trying next...`));
        tryStart(startPort + 1, attempts + 1);
      }
    });

    child.stdout.on("data", (data) => process.stdout.write(data));

    child.on("error", (e) => {
      if (e.message.includes("EADDRINUSE") && !hasError) {
        console.log(warn(`Port ${startPort} is in use, trying next...`));
        tryStart(startPort + 1, attempts + 1);
      } else if (!hasError) {
        console.log(err(`Failed to start: ${e.message}`));
        process.exit(1);
      }
    });

    child.on("close", (code) => {
      if (!hasError) process.exit(code || 0);
    });

    process.on("SIGINT", () => child.kill("SIGINT"));
    process.on("SIGTERM", () => child.kill("SIGTERM"));
  };

  tryStart(port);
}

// ─── Docker helpers ───

function ensureDockerCompose(ports) {
  const composeFile = path.join(ROOT, "docker-compose.db.yml");
  if (fs.existsSync(composeFile)) return;

  const content = `version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: maestria-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maestria_lms
    ports:
      - "${ports.postgresql}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    container_name: maestria-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: maestria_lms
    ports:
      - "${ports.mongodb}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
`;
  fs.writeFileSync(composeFile, content, "utf8");
  console.log(ok("Created docker-compose.db.yml"));
}

function startDockerServices(provider) {
  if (provider !== "postgresql" && provider !== "mongodb") return;

  console.log(info("Checking Docker services..."));
  try {
    execSync("docker compose -f docker-compose.db.yml ps", {
      cwd: ROOT,
      stdio: "pipe",
      timeout: 5000,
    });
  } catch {
    console.log(info("Starting Docker services..."));
    try {
      execSync("docker compose -f docker-compose.db.yml up -d", {
        cwd: ROOT,
        stdio: "inherit",
      });
      console.log(ok("Docker services started"));
    } catch {
      console.log(warn("Docker failed to start. Ensure Docker is running."));
    }
  }
}

// ─── Main ───

async function main() {
  console.log(head("\n  🎓 Maestria LMS — Setup\n"));

  const pm = env.detectPackageManager(ROOT);
  console.log(info(`Package manager: ${pm.name}`));

  const ports = await env.findAllPorts();
  console.log(ok(`App port: ${ports.app}`));
  console.log(info(`DB ports — PostgreSQL: ${ports.postgresql}, MongoDB: ${ports.mongodb}`));

  // Check for forced provider via --db <provider>
  const forcedProvider = process.argv.includes("--db")
    ? process.argv[process.argv.indexOf("--db") + 1]
    : null;
  if (forcedProvider) {
    console.log(info(`Forced database: ${forcedProvider}`));
  }

  const dbConfig = await validateAndGenerateEnv(ports, forcedProvider);

  // Docker setup for PostgreSQL / MongoDB
  if (dbConfig.docker || (dbConfig.provider === "postgresql" && env.checkDocker())) {
    ensureDockerCompose(ports);
    startDockerServices(dbConfig.provider);
  }

  runPrerequisites(pm, dbConfig.provider);
  startDevServer(pm, ports.app);
}

main().catch((e) => {
  console.log(err(`Fatal: ${e.message}`));
  process.exit(1);
});
